services:
  influx:
    image: "influxdb:2.1.1"
    ports:
      - "8086:8086"
    volumes:
      - $PWD/data:/var/lib/influxdb2
      - $PWD/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_V2_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_V2_TOKEN}
  grafana:
    image: "grafana/grafana:8.4.1"
    ports:
      - "3000:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana
    depends_on:
      - "influx"
  backend:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - "influx"
    environment:
      INFLUXDB_V2_URL: http://influx:8086
      INFLUXDB_V2_ORG: ${INFLUXDB_V2_ORG}
      INFLUXDB_V2_TOKEN: ${INFLUXDB_V2_TOKEN}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
