services:
  influx:
    restart: unless-stopped
    image: "influxdb:2.1.1"
    ports:
      - "8086:8086"
    volumes:
      - influx_storage:/var/lib/influxdb2
      - influx_storage:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_V2_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_V2_TOKEN}
  grafana:
    restart: unless-stopped
    image: "grafana/grafana:8.4.1"
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    depends_on:
      - "influx"
  backend:
    restart: unless-stopped
    build: .
    ports:
      - "8000:80"
    depends_on:
      - "influx"
    environment:
      INFLUXDB_V2_URL: http://influx:8086
      INFLUXDB_V2_ORG: ${INFLUXDB_V2_ORG}
      INFLUXDB_V2_TOKEN: ${INFLUXDB_V2_TOKEN}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}

volumes:
  grafana_storage:
  influx_storage:
